### PR TITLE
Feature/insert text

### PR DESCRIPTION
**Pull request by jwillinghalpern**
Adds support for insert text and a reusable Target enum, since many steps like EDAPI, Insert From URL, Insert Calculated Result etc support a target var/field.

### CODE REVIEW

**Comment by jwillinghalpern** [comment]
Sorry, for the noise, I want to work a bit more on this before offering a PR, perhaps supporting more steps.

**Comment by jwillinghalpern** [comment]
Wow, looking more at this, and having parsed a few more script steps I checked how many <Parameter> `type`s there were in fmSyntaxColorizer and got this massive list. Getting this tool to parity with the XML seems like a really big job, even though many of the steps have the same exact internal structure (e.g. Insert Current Date/Current Time/Current User Name etc).

```
// <Parameter type="TYPE_HERE">
Animation
Author
Boolean
Button1 // can also have a value="USER ENTERED LABEL HERE"
Button2 // can also have a value="USER ENTERED LABEL HERE"
Button3 // can also have a value="USER ENTERED LABEL HERE"
Calculation
Camera
Comment
Condition
CustomDebugInfo
CustomMenuSet
DataSourceReference
DisableExternalControls
DisableInteraction
Duration
Email
End
ErrorCode
ErrorMessage
Export
Field1
Field2
Field3
FieldReference
FindRequest
FunctionRef
Hide
ImportField
JSONOutput
Keywords
Label
Latitude
LayoutReferenceContainer
List
Location
Longitude
Major
Message
Minor
Monitor
Name
New
Object
Old
Options
PageSetup
Parameter
Password
PauseInBackground
Portal
Presentation
Print
PrivilegeSetReference
Prompt
Radius
ReadMultiple
Records
Related
Resolution
Restore
SQL
ScriptReference
Select
Sequence
SortSpecification
Source
Start
Subject
Target
Text
Timeout
Title
URL
UUID
UniversalPathList
Variable
Voice
Volume
Wait
WindowReference
Worksheet
Zoom
across
action
case
direction
find
from
id
name
operation
perform
position
replace
size
type
whole
within
```

There are even 40+ <Boolean> types!

My original thought was to encode all of those different types into enum variants, and that _may_ still be the best approach, but I was just surprised to see how much variety exists!

**Comment by bc-m** [comment]
> Wow, looking more at this, and having parsed a few more script steps I checked how many `<Parameter>` (The kind that lives within `<ParameterValues>` tags) `type`s there were in fmSyntaxColorizer and got this massive list. Getting this tool to parity with the XML seems like a really big job, even though many of the steps have the same exact internal structure (e.g. Insert Current Date/Current Time/Current User Name etc).
> 
> [...]
> 
> There are even 40+ `<Boolean>` types!
> 
> My original thought was to encode all of those different types into enum variants, and that _may_ still be the best approach, but I was just surprised to see how much variety exists!

I like your approach and think we should parse the parameters per script step as we encounter them. It would be great to have a checklist. Maybe you can create an issue with a checklist like #28?

**Comment by jwillinghalpern** [comment]
Good idea. I'm sort of toying with the concept of whether all/most steps that use that <ParameterValues> approach can instead use generalized `parameterized` sanitize function that simply parses the the <Parameters> into a vec and then prints them in the order they appear, separated by ` ; `. I'm letting this one percolate a bit. Meanwhile I like your approach of just cannibalizing stuff from my messy fork as you see fit and then when I come back I can freshly branch from your main branch again since mine is now divergent.

**Comment by bc-m** [comment]
I have continued to follow your approach and created a good point with [v0.3.1](https://github.com/bc-m/fm-xml-export-exploder/releases/tag/v0.3.1), which you are welcome to pick up on again. 

We now have a single script step parser (legacy ones still exist, but should be easily merged into the generalized one). All script-steps now parsed [here](https://github.com/bc-m/fm-xml-export-exploder/blob/main/src/script_steps/sanitize.rs) and all parameters parsed [here](https://github.com/bc-m/fm-xml-export-exploder/blob/main/src/script_steps/parameters/parameter_values.rs).

**Pull request closed without merging**
